#!/usr/bin/env python3
"""Phase 1 data prep: Repeat Factor Sampling (Gupta et al., LVIS, CVPR 2019).

  f(c) = fraction of TRAIN images containing >= 1 box of class c
  r(c) = max(1, sqrt(t / f(c)))
  r(i) = max over classes present in image i of r(c)

Ultralytics has no sampler hook, so the repeat schedule is materialised as an
expanded image-path list (a .txt consumed via the data yaml). Image FILES are
never duplicated - only path entries repeat.

Rounding: STOCHASTIC (seeded). n_i = floor(r_i) + Bernoulli(frac(r_i)).
Chosen over ceil() because ceil systematically inflates the epoch - an image
with r_i = 1.01 would be duplicated outright - whereas stochastic rounding is
unbiased, E[n_i] = r_i. The draw is made once and frozen into the list, so the
schedule is identical across epochs and reproducible from SEED.

Writes only under 11_improvements/. Read-only on MDImageDataset/.
"""
import argparse
import csv
import math
import random
from collections import defaultdict

from paths import (  # noqa: I001 - must precede `common`, it puts 10_diagnostics on sys.path
    DATA_DIR, IMPROVE_DIR, NC, RFS_DIR, SEED, SRC_LABELS, ensure_variant_tree, variant_tree,
)
from common import CLASS_NAMES  # noqa: E402 - 10_diagnostics/common.py

MAX_EPOCH_GROWTH = 2.5


def load_train_class_presence():
    """-> (list of (stem, set_of_classes), images_per_class dict)."""
    per_image = []
    images_per_class = defaultdict(int)
    for lbl in sorted(SRC_LABELS["train"].glob("*.txt"), key=lambda p: p.stem):
        classes = set()
        with open(lbl.resolve()) as f:
            for line in f:
                line = line.strip()
                if line:
                    classes.add(int(line.split()[0]))
        per_image.append((lbl.stem, classes))
        for c in classes:
            images_per_class[c] += 1
    return per_image, images_per_class


def repeat_factors(images_per_class, n_images, t):
    """r(c) per class."""
    r_c = {}
    for c in range(NC):
        n_c = images_per_class.get(c, 0)
        f_c = n_c / n_images if n_images else 0.0
        r_c[c] = max(1.0, math.sqrt(t / f_c)) if f_c > 0 else 1.0
    return r_c


def image_repeats(per_image, r_c, rng):
    """r(i) then stochastic rounding -> integer repeat count per image."""
    out = []
    for stem, classes in per_image:
        r_i = max((r_c[c] for c in classes), default=1.0)
        floor = math.floor(r_i)
        n_i = floor + (1 if rng.random() < (r_i - floor) else 0)
        out.append((stem, r_i, max(1, n_i)))
    return out


def epoch_size_for_t(per_image, images_per_class, n_images, t):
    """Expected (unrounded) epoch size for a candidate t - used for the sweep table."""
    r_c = repeat_factors(images_per_class, n_images, t)
    return sum(max((r_c[c] for c in classes), default=1.0) for _, classes in per_image)


def write_list(path, image_paths):
    """One image path per line (repeats allowed). Paths must stay UNRESOLVED.

    check_det_dataset() calls .resolve() on directory entries, which follows the
    data/<variant> symlinks back into read-only MDImageDataset/ and drops the
    label .cache there. Paths listed inside a .txt are read verbatim, so routing
    every split through a list keeps all writes inside 11_improvements/.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        f.writelines(f"{p}\n" for p in image_paths)


def write_yaml(path, data_root, train_entry, val_entry):
    lines = [
        "# generated by 11_improvements/make_rfs_list.py - do not hand-edit",
        f"path: {data_root}",
        f"train: {train_entry}",
        f"val: {val_entry}",
        "",
        f"nc: {NC}",
        "",
        "names:",
    ]
    lines += [f"  {c}: {CLASS_NAMES[c]}" for c in range(NC)]
    path.write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--t", type=float, default=1e-3, help="RFS threshold t")
    ap.add_argument("--seed", type=int, default=SEED)
    args = ap.parse_args()

    RFS_DIR.mkdir(parents=True, exist_ok=True)
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    per_image, images_per_class = load_train_class_presence()
    n_images = len(per_image)

    t = args.t
    r_c = repeat_factors(images_per_class, n_images, t)
    rng = random.Random(args.seed)
    repeats = image_repeats(per_image, r_c, rng)
    eff = sum(n for _, _, n in repeats)

    # Guard from the spec. NOTE: the spec says "raise t" if the epoch grows past
    # 2.5x, but r(c) = sqrt(t/f(c)) is INCREASING in t - raising t makes the epoch
    # bigger. Lowering t is what shrinks it, so the guard reduces t.
    adjustments = []
    while eff > MAX_EPOCH_GROWTH * n_images:
        new_t = t / 2
        adjustments.append((t, eff, new_t))
        t = new_t
        r_c = repeat_factors(images_per_class, n_images, t)
        rng = random.Random(args.seed)
        repeats = image_repeats(per_image, r_c, rng)
        eff = sum(n for _, _, n in repeats)

    print(f"{'cid':>4} {'class_name':<32} {'imgs':>6} {'f(c)':>10} {'r(c)':>8}")
    for c in range(NC):
        n_c = images_per_class.get(c, 0)
        f_c = n_c / n_images
        print(f"{c:>4} {CLASS_NAMES[c]:<32} {n_c:>6} {f_c:>10.6f} {r_c[c]:>8.4f}")

    n_boosted = sum(1 for c in range(NC) if r_c[c] > 1.0)
    print()
    print(f"t (final)                 : {t:g}")
    for old_t, old_eff, new_t in adjustments:
        print(f"  adjusted: t={old_t:g} gave {old_eff} imgs (> {MAX_EPOCH_GROWTH}x) -> t={new_t:g}")
    print(f"classes with r(c) > 1     : {n_boosted} / {NC}")
    print(f"original epoch size       : {n_images}")
    print(f"effective epoch size      : {eff}")
    print(f"growth factor             : {eff / n_images:.4f}x")

    print("\nsweep of candidate t (expected epoch size, before rounding):")
    print(f"{'t':>10} {'epoch':>10} {'growth':>8} {'classes r>1':>12}")
    for cand in (1e-3, 5e-3, 1e-2, 2e-2, 3e-2, 5e-2, 1e-1):
        est = epoch_size_for_t(per_image, images_per_class, n_images, cand)
        rc = repeat_factors(images_per_class, n_images, cand)
        print(f"{cand:>10g} {est:>10.0f} {est / n_images:>7.3f}x {sum(1 for c in range(NC) if rc[c] > 1.0):>12}")

    # ---- write artefacts ----
    tag = f"t{t:g}"
    ensure_variant_tree("rfs")
    ensure_variant_tree("control")

    val_stems = sorted(p.stem for p in SRC_LABELS["val"].glob("*.txt"))

    # RFS train list: image paths repeated n_i times
    rfs_images = variant_tree("rfs") / "images" / "train"
    list_path = RFS_DIR / f"train_rfs_{tag}.txt"
    rfs_lines = []
    for stem, _, n_i in repeats:
        rfs_lines.extend([str(rfs_images / f"{stem}.jpg")] * n_i)
    write_list(list_path, rfs_lines)
    write_list(RFS_DIR / "val_rfs.txt",
               [str(variant_tree("rfs") / "images" / "val" / f"{s}.jpg") for s in val_stems])

    # control lists: every train image exactly once
    ctrl_train = RFS_DIR / "train_control.txt"
    ctrl_val = RFS_DIR / "val_control.txt"
    write_list(ctrl_train,
               [str(variant_tree("control") / "images" / "train" / f"{stem}.jpg") for stem, _ in per_image])
    write_list(ctrl_val,
               [str(variant_tree("control") / "images" / "val" / f"{s}.jpg") for s in val_stems])

    factors_path = RFS_DIR / f"rfs_factors_{tag}.csv"
    with open(factors_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["class_id", "class_name", "train_images", "f_c", "r_c"])
        for c in range(NC):
            n_c = images_per_class.get(c, 0)
            w.writerow([c, CLASS_NAMES[c], n_c, round(n_c / n_images, 8), round(r_c[c], 6)])

    rfs_yaml = IMPROVE_DIR / f"data_rfs_{tag}.yaml"
    write_yaml(rfs_yaml, variant_tree("rfs"), list_path, RFS_DIR / "val_rfs.txt")

    control_yaml = IMPROVE_DIR / "data_control.yaml"
    write_yaml(control_yaml, variant_tree("control"), ctrl_train, ctrl_val)

    print(f"\nwrote {list_path}  ({eff} lines)")
    print(f"wrote {factors_path}")
    print(f"wrote {rfs_yaml}")
    print(f"wrote {control_yaml}")
    print(f"\nrun name for this t: y11m_rfs_{tag}")


if __name__ == "__main__":
    main()
